### ISSUE TITLE
Add CSS Styling

### ISSUE THREAD

**Issue by nikiljos** [nikiljos/simple-calc#2]

**Comment by vandana1499** [comment]
will u help me with description?

**Comment by nikiljos** [comment]
You can make the form mobile friendly, also can add hover effect to the buttons.

**Comment by nikiljos** [comment]
@vandana1499 Do u plan to do it?

**Comment by vandana1499** [comment]
I will work on it.

**Comment by nikiljos** [comment]
@vandana1499  I already got some pull requests with UI changes. Thanks for your time.

**Comment by vandana1499** [comment]
Ohk , I would like to send some small changes that will enhance some functioning.
