### ISSUE TITLE
Bootstrap CSS fix

### ISSUE THREAD

**Issue by nikiljos** [nikiljos/simple-calc#7]
**The buttons are not centered in large screen view**
![image](https://user-images.githubusercontent.com/57913645/95174475-be7a9600-07d7-11eb-937f-9928e928fd52.png)

**The top and bottom buttons need to be separated in Mobile view**
![image](https://user-images.githubusercontent.com/57913645/95174790-321ca300-07d8-11eb-8e3a-6be902afd9dc.png)

**Comment by arkumari2000** [comment]
I would like to fix the bug.
Can you please assign it to me?

**Comment by omarobaji** [comment]
I would like you to assign this to me please!

**Comment by dishak331** [comment]
I would like to work on this

**Comment by nikiljos** [comment]
Thank you all.... Since @arkumari2000 asked first, i am assigning it to her.

**Comment by nikiljos** [comment]
I already received a PR fixing this. Thanks to all......
